{% set version = environ.get("HOLOSCAN_VERSION", "4.4.0.1") %}

package:
  name: holoscan
  version: {{ version }}

source:
  - url: "https://files.pythonhosted.org/packages/a2/aa/c582ff9a4efb89b775c55f3514e08e95021002c16b7847a9bfdd260854f1/holoscan_cu13-4.4.0-cp310-cp310-manylinux_2_35_x86_64.whl"  # [linux64 and (cuda_compiler_version or "").startswith("13") and py == 310]
    sha256: "b2584560307ae126be88091414d1112b6a1b764320db22b17df66979158673f3"  # [linux64 and (cuda_compiler_version or "").startswith("13") and py == 310]
  - url: "https://files.pythonhosted.org/packages/c3/82/e0ea0d6e116befbbe8ca58579b201fccf780cebbbbf1890cc77da6579ff4/holoscan_cu13-4.4.0-cp311-cp311-manylinux_2_35_x86_64.whl"  # [linux64 and (cuda_compiler_version or "").startswith("13") and py == 311]
    sha256: "62e814d10105e66f9fc6794994cbbb0d8b580a4960278b11334bfcd06bcb7bd5"  # [linux64 and (cuda_compiler_version or "").startswith("13") and py == 311]
  - url: "https://files.pythonhosted.org/packages/ae/b2/dfe6ebdfb4653c9b50848321d3b5ed9a6bce5939fd7fd08bc90401b02c6c/holoscan_cu13-4.4.0-cp312-cp312-manylinux_2_35_x86_64.whl"  # [linux64 and (cuda_compiler_version or "").startswith("13") and py == 312]
    sha256: "19788eeb08adabe9231080fc178194296c00ec95f0947af0fe5a34df2ff19e9c"  # [linux64 and (cuda_compiler_version or "").startswith("13") and py == 312]
  - url: "https://files.pythonhosted.org/packages/57/bb/c5c84381f3e81341f0503a34e354a322b8cbca956154832d06ac89359c98/holoscan_cu13-4.4.0-cp313-cp313-manylinux_2_35_x86_64.whl"  # [linux64 and (cuda_compiler_version or "").startswith("13") and py == 313]
    sha256: "39cf52755d26a751d4d380b9e440309ce8e6ab864947d9096ce22877b6c9dd99"  # [linux64 and (cuda_compiler_version or "").startswith("13") and py == 313]

  - url: "https://files.pythonhosted.org/packages/00/49/b2884af9f584a787bf6d39633fd868661a11dfab8ed7c4118e18974d0956/holoscan_cu13-4.4.0-cp310-cp310-manylinux_2_35_aarch64.whl"  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa" and py == 310]
    sha256: "c735af18cdb1ea52090376e18ba0fdf7963e20f4c99afc7d58678e512032e688"  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa" and py == 310]
  - url: "https://files.pythonhosted.org/packages/49/de/5d28e94f210ff4abdc05f6f0373baf041ffd4cc946ca8545d1e67ebf4d5e/holoscan_cu13-4.4.0-cp311-cp311-manylinux_2_35_aarch64.whl"  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa" and py == 311]
    sha256: "424bbc33f1490d1db8027f6d7fca5a1e19d804280b9134c3a784722ede260b1a"  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa" and py == 311]
  - url: "https://files.pythonhosted.org/packages/6a/8e/b00229aa0134334b7937d26fc754362ebcf6636c8fa7d696cdffcc953f53/holoscan_cu13-4.4.0-cp312-cp312-manylinux_2_35_aarch64.whl"  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa" and py == 312]
    sha256: "b35238e3433358b71155d50236e7f4431d5c94cda94a9f809e6f509df80be9cd"  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa" and py == 312]
  - url: "https://files.pythonhosted.org/packages/80/1a/e617f7e67841950ece99c67807dc3d0dd077d78e0621128900ad9241e2b3/holoscan_cu13-4.4.0-cp313-cp313-manylinux_2_35_aarch64.whl"  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa" and py == 313]
    sha256: "c6bbd9fdcc51006cd691fe5337152bb1401b4e81b976c1a7f7df246a29f1e390"  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa" and py == 313]

build:
  number: 0
  skip: true  # [not (linux64 or aarch64)]
  skip: true  # [cuda_compiler_version in (None, "None", "") or (cuda_compiler_version or "").startswith("11") or (cuda_compiler_version or "").startswith("12")]
  skip: true  # [py<310 or py>313]
  missing_dso_whitelist:
    - "*libcuda.so*"              # driver, not provided by any conda package
    - "*librmm.so*"               # RMM, available in RAPIDS channel
  ignore_run_exports:
    - cuda-version

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cuda') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python
    - cf-nvidia-tools 1  # [linux]
  host:
    - libholoscan {{ version }}
    - cuda-version {{ cuda_compiler_version }}
    - python
    - setuptools
    - pip
  run:
    - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
    - cloudpickle >=3.0
    - cuda-version >={{ cuda_compiler_version_min }}
    - cupy
    - libholoscan {{ version }}.*
    - cuda-cudart
    - python

test:
  # imports:
  #   - holoscan
  requires:
    - pip
  commands:
    - test -d $SP_DIR/holoscan/
    - pip check

about:
  home: https://docs.nvidia.com/cuda/holoscan/
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_file:
    - LICENSE
    - NOTICE
  license_url: https://developer.download.nvidia.com/assets/Clara/NVIDIA_Clara_EULA.pdf
  summary: NVIDIA Holoscan python bindings
  description: |
    NVIDIA Holoscan python bindings

extra:
  recipe-maintainers:
    - conda-forge/cuda
  feedstock-name: holoscan
