{% set version = environ.get("HOLOSCAN_VERSION", "4.5.0.0") %}

package:
  name: holoscan
  version: {{ version }}

source:
  - url: "https://files.pythonhosted.org/packages/c6/0a/fb3332c4c99b18e86d99cbc9000860be7b1e7cd228d037daee7525b53fbc/holoscan_cu13-4.5.0-cp310-cp310-manylinux_2_35_x86_64.whl"  # [linux64 and (cuda_compiler_version or "").startswith("13") and py == 310]
    sha256: "0f5329a34febf3fe8f0f32f99e05614da4275fca97977141da2022fa169d7507"  # [linux64 and (cuda_compiler_version or "").startswith("13") and py == 310]
  - url: "https://files.pythonhosted.org/packages/85/8c/e448b2c38cf1df1af56563eabf7a927e81dbcfbea343bb32fa76d00d439a/holoscan_cu13-4.5.0-cp311-cp311-manylinux_2_35_x86_64.whl"  # [linux64 and (cuda_compiler_version or "").startswith("13") and py == 311]
    sha256: "645478ce5e28aa2b060416d73bed46a61287b7286b924e9ff4f38a390c8f8b9e"  # [linux64 and (cuda_compiler_version or "").startswith("13") and py == 311]
  - url: "https://files.pythonhosted.org/packages/2b/f5/79841e72efe0b7d0f43245b861594bf42dfe2641c1e1470330033ce069f8/holoscan_cu13-4.5.0-cp312-cp312-manylinux_2_35_x86_64.whl"  # [linux64 and (cuda_compiler_version or "").startswith("13") and py == 312]
    sha256: "35f554bbc0a0d74d0c81d509532dc7113d37e98c091e1afeeeca39021b9648a4"  # [linux64 and (cuda_compiler_version or "").startswith("13") and py == 312]
  - url: "https://files.pythonhosted.org/packages/da/52/049b4acfd87eec55ac6346bcb8d07c9c74435d24c55acc8576dbfdf023f9/holoscan_cu13-4.5.0-cp313-cp313-manylinux_2_35_x86_64.whl"  # [linux64 and (cuda_compiler_version or "").startswith("13") and py == 313]
    sha256: "5ba15d60ac29011cadf8192994743fe9cdd86dfc9e61eff95d83e173431ab8e5"  # [linux64 and (cuda_compiler_version or "").startswith("13") and py == 313]

  - url: "https://files.pythonhosted.org/packages/8d/aa/85d0d354decb982aa938bf1c837194e04d56addf3f6ca2b8ba672191e7fe/holoscan_cu13-4.5.0-cp310-cp310-manylinux_2_35_aarch64.whl"  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa" and py == 310]
    sha256: "cdd199abb92bd024b255d9547f6e7fa83926d68a9af9dfedee23a2ca6ce56fd5"  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa" and py == 310]
  - url: "https://files.pythonhosted.org/packages/ac/8e/fec16af1842ff7805f7a3f84697d0c8bcfe4bb1f82fc5d2e6a1e60f37fb4/holoscan_cu13-4.5.0-cp311-cp311-manylinux_2_35_aarch64.whl"  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa" and py == 311]
    sha256: "87495e98ad4b1c2ef9740b6ac9bb8656b411caea71df9577f2348902ba9cedf6"  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa" and py == 311]
  - url: "https://files.pythonhosted.org/packages/0f/ba/24665bd92b9b208fc8704395cc89641e74f0cfad7b0aa4b15f9066102a76/holoscan_cu13-4.5.0-cp312-cp312-manylinux_2_35_aarch64.whl"  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa" and py == 312]
    sha256: "36ba219154f30003893c8b21fa57e12be5f166c9dff0be0dd1d1d426b170dcb4"  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa" and py == 312]
  - url: "https://files.pythonhosted.org/packages/83/3c/cdddc9a25933eaf5262f17fc57ff08d457b5edf1fb8ac06ce36a0afacc38/holoscan_cu13-4.5.0-cp313-cp313-manylinux_2_35_aarch64.whl"  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa" and py == 313]
    sha256: "1b7961c5e1a7454ff8e89833a840a73a11ed255148f6e7d91873ef4fdba0fbdf"  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa" and py == 313]

build:
  number: 0
  skip: true  # [not (linux64 or aarch64)]
  skip: true  # [cuda_compiler_version in (None, "None", "") or (cuda_compiler_version or "").startswith("11") or (cuda_compiler_version or "").startswith("12")]
  skip: true  # [py<310 or py>313]
  missing_dso_whitelist:
    - "*libcuda.so*"              # driver, not provided by any conda package
    - "*librmm.so*"               # RMM, available in RAPIDS channel
  ignore_run_exports:
    - cuda-version

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cuda') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python
    - cf-nvidia-tools 1  # [linux]
  host:
    - libholoscan {{ version }}
    - cuda-version {{ cuda_compiler_version }}
    - python
    - setuptools
    - pip
  run:
    - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
    - cloudpickle >=3.0
    - cuda-version >={{ cuda_compiler_version_min }}
    - cupy
    - libholoscan {{ version }}.*
    - cuda-cudart
    - python

test:
  # imports:
  #   - holoscan
  requires:
    - pip
  commands:
    - test -d $SP_DIR/holoscan/
    - pip check

about:
  home: https://docs.nvidia.com/cuda/holoscan/
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_file:
    - LICENSE
    - NOTICE
  license_url: https://developer.download.nvidia.com/assets/Clara/NVIDIA_Clara_EULA.pdf
  summary: NVIDIA Holoscan python bindings
  description: |
    NVIDIA Holoscan python bindings

extra:
  recipe-maintainers:
    - conda-forge/cuda
  feedstock-name: holoscan
